---
title: "Ethical Approaches"
---

### The Fairness Approach
The fairness approach asserts that all individuals should be treated equally. This relates to the politician's argument in the sense that they believe they should be treated like any other Twitter user, who has an expectation of privacy for deleted tweets. According to this view of the fairness approach, if ordinary twitter accounts are able to keep their data private, then so should politicians.


### The Utilitarian Approach
The utilitarian approach states that the morally right action is the one that produces the greatest good for the greatest number of epople. This approach applies to Politwoops' argument in this case. Politiwoops could make the argument that giving a full, unfiltered view of a politician's thoughts and feelings would give the most complete picture of information to the general electorate in order to make a decision on election day.


### The Rights Approach
The rights approach is one that asserts people have rights by nature of existence as a human, one of which is often a right to privacy. The Twitter organization could use the rights approach to defend their position of revoking Politiwoops' access by citing a violation of the terms of service. If Twitter upholds users' right to privacy through a previously agreed-upon terms of service, then they can defend their decision as protecting a politician's right to privacy.